[workspace]
resolver = "2"

members = [
    "irwindow",
]

[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
[target.x86_64-pc-windows-msvc]

[target.x86_64-apple-darwin]